# Generated by Django 2.2.1 on 2019-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'message',
                'managed': True,
            },
        ),
    ]
